name: Sync Docs Content

on:
  push:
    branches:
      - dev
    paths:
      - "content/docs/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deondocs
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout innovation
        uses: actions/checkout@v2
        with:
          repository: Deonhub-LTD/innovation
          path: innovation
          token: ${{ secrets.INNOVATION_REPO_PAT }}
          fetch-depth: 0

      - name: Sync docs content
        run: |
          # Remove existing docs content in innovation repo
          rm -rf innovation/src/content/docs/*

          # Copy new content from deondocs
          cp -r content/docs/* innovation/src/content/docs/

          # Setup git in innovation repo
          cd innovation
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'

          # Commit and push if there are changes
          git add src/content/docs
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync docs content from deondocs (dev branch)"
            git push
          fi

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.INNOVATION_REPO_PAT }}
          commit-message: Sync docs content from dev to main
          title: "Sync docs content from dev to main"
          body: "This PR syncs the latest docs content from the dev branch to the main branch."
          branch: sync-docs-to-main
          base: main
